apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bia3z8wgu-go 
  janus-idp.io/tekton: bia3z8wgu-go
  backstage.io/kubernetes-id: bia3z8wgu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bia3z8wgu-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  