apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bia3z8wgu-go-gitops
  description: This is GitOps manifest for bia3z8wgu-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: bia3z8wgu-go
    janus-idp.io/tekton: bia3z8wgu-go
    backstage.io/kubernetes-id: bia3z8wgu-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bia3z8wgu-go
